openapi: "3.0.0"
info:
  title: API documentation
  version: "1.0"
paths:
  /nodes/{node_id}/children:
    get:
      summary: Get the child nodes of the given node in the organizational tree
      parameters:
        - in: path
          name: node_id
          schema:
            type: integer
          description: The Id of the Node that the children will be searched for
          example: 5
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
                  description: Language of the names in the results
                  enum:
                    - english
                    - italian
                search_keyword:
                  type: string
                  description: Optional keyword to filter the results
                  example: Managers
                page_num:
                  type: integer
                  description: Which page of the result to retrieve
                  example: 2
                page_size:
                  type: integer 
                  description: Sets the page size of the results
                  example: 100
              required:
                - node_id
                - language
      responses:
        '200':
          description: List of child nodes
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodes:
                    type: array 
                    description: List of child node objects
                    items:
                      type: object
                      properties:
                        node_id:
                          type: integer
                          description: Id of the node
                          example: 5
                        name:
                          type: string
                          description: Name of the node
                          example: Managers
                        children_count:
                          type: integer
                          description: Count of direct children of this node
                          example: 2
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error


        